// all the database names will be stored here
// and we will be accessing them from here only

module.exports = {
  users: 'users',
  user_addresses: 'user_addresses',
  categories: 'categories',
  sub_categories: 'sub_categories',
  super_sub_categories: 'super_sub_categories',
  product_attributes: 'product_attributes',
  product_brands: 'product_brands',
  variants: 'variants',
  variants_attribute: 'variants_attribute',
  products: 'products',
  product_images: 'product_images',
  car_brands: 'car_brands',
  car_models: 'car_models',
  car_lists: 'car_lists',
  orders: 'orders',
  order_details: 'order_details',
  order_statuses: 'order_statuses',
  order_status_logs: 'order_status_logs',
  delivery_types: 'delivery_types',
  banners: 'banners',
  banner_product_associations: 'banner_product_associations',
  coupons: 'coupons',
  discounts: 'discounts',
  product_discount_associations: 'product_discount_associations',
  product_attributes_associations: 'product_attributes_associations',
  attributes_combinations: 'attributes_combinations',
  installers: 'installers',
  subscribed_customers: 'subscribed_customers',
  stories: 'stories',
  static_pages: 'static_pages',
  store_infos: 'store_infos',
  testimonials: 'testimonials',
  admins: 'admins',
  customers: 'customers',
  dealers: 'dealers',
  otps:'otps',
  stories_product_associations: 'stories_product_associations',
  carts: 'carts',
  wishlists: 'wishlists',
};
